### ISSUE TITLE
ID3 Tagging Failed

### ISSUE THREAD

**Issue by bcsanford** [nega0/pianobarfly#52]
Downloaded and made 2013-08-17@1700

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=13.04
DISTRIB_CODENAME=raring
DISTRIB_DESCRIPTION="Ubuntu 13.04"

Linux 3.8.0-27-generic #40-Ubuntu SMP Tue Jul 9 00:17:05 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

latest commit 21dc59298b
nega authored 12 days ago

|>  "Otherside" by "Red Hot Chili Peppers" on "Californication"
/!\ Error opening the temporary file (./mp3/pianobarfly-QzC1LE) (2:No such file or directory).
/!\ Error writing the tag to the file (Red_Hot_Chili_Peppers/Californication/Red_Hot_Chili_Peppers-Otherside.m4a).

**Comment by phillip-toone** [comment]
I am experiencing this same problem. I checked to ensure that my version includes the fix nega authored on Aug 23, 2013 before posting this.

**Comment by phillip-toone** [comment]
I am wrong. This error is slightly different.  The second line of the error is different:

/!\ Could not open the temporary file (./mp3/pianobarfly-hKEggi) (2:No such file or directory).
/!\ Failed to write the tag.

I don't know if this matters but a file is written to ./mp3/%artist/%album/%artist-%title during the Recording process.  I would think the program should try to access that file, not the file ./mp3/pianobarfly-XXXXXX

Also, this problem did not occur when I was using it to stream files in AAC+ 64k format.  It just started after I upgraded to Pandora One and removed the comment tags from the recommended last 8 lines of the ~/.config/pianobarfly/config file.

**Comment by phillip-toone** [comment]
Okay, I figured out a workaround for this.  For whatever reason when I use a relative path for the audio file directory in the configuration file I get this error.  But when I use an absolute path I don't get this error.

To be more clear when recording 192k mp3 this produces the error:
audio_file_dir = ./mp3

But this fixes the problem:
audio_file_dir = /some/absolue/path/on/you/system/you/can/write/to

Again, I do not get this problem at all when recording streams from a AAC+ 64k format, only when recording from a 192k mp3 streams on Pandora One.
